const $ = (s, r = document) => r.querySelector(s);
const app = $("#app"), modalRoot = $("#modal-root"), toastEl = $("#toast");
const money = n => "$" + Number(n).toFixed(2);
const places = [
  ["Downtown · E Choctaw Avenue",34.932,-95.768],
  ["McAlester Regional Health Center",34.927,-95.744],
  ["Walmart · S George Nigh Expressway",34.894,-95.77],
  ["Chadick Park",34.946,-95.764],
  ["McAlester Public Library",34.933,-95.77],
  ["Old Town · Main Street",34.934,-95.775],
  ["McAlester High School",34.951,-95.783],
  ["Shopping · E Carl Albert Parkway",34.929,-95.735]
].map((p,i)=>({id:i,name:p[0],lat:p[1],lng:p[2]}));
const baseDrivers = [
  ["D1","Travis Miller","Toyota","Camry","Silver","OKD-214","918-555-0101",34.933,-95.77,true,true],
  ["D2","Kayla Reed","Nissan","Rogue","Black","OKD-809","918-555-0102",34.936,-95.759,true,true],
  ["D3","Derek Price","Ford","Escape","Blue","OKD-441","918-555-0103",34.922,-95.745,true,true],
  ["D4","Avery Brooks","Honda","Accord","White","OKD-118","918-555-0104",34.917,-95.761,true,true],
  ["D5","Morgan Davis","Kia","Sportage","Gray","OKD-672","918-555-0105",34.941,-95.786,true,true],
  ["D6","Riley West","Hyundai","Tucson","Red","OKD-330","918-555-0106",34.907,-95.779,true,true],
  ["D7","Cameron Cole","Toyota","Corolla","White","OKD-502","918-555-0107",34.954,-95.752,false,true],
  ["D8","Taylor James","Chevrolet","Malibu","Black","OKD-734","918-555-0108",34.924,-95.797,false,true]
];
const names = ["Maya Thompson","Eli Parker","Nora James","Caleb Ross","Lena Ortiz","Brian Cole","Ivy Johnson","Sam Walker","June Harper","Owen Clark","Tara Hill","Miles Young","Grace Allen","Theo King","Paige Bell","Will Scott","Ruth Adams","Jude Morris","Hope Turner","Alex Rivera","Mona Lee","Ian Foster","Kate Price","Drew Nelson","Lori Stone","Chris Gray","Anna Reed","Jay Brooks"];
let state;
function dist(a,b){ const x=(a.lat-b.lat)*69, y=(a.lng-b.lng)*57; return Math.max(1.2,Math.hypot(x,y)*1.35+.6); }
function fare(mi){ return +(state.pricing.base + state.pricing.mile * mi).toFixed(2); }
function seedDrivers(){ return baseDrivers.map(d=>({id:d[0],name:d[1],make:d[2],model:d[3],color:d[4],plate:d[5],phone:d[6],lat:d[7],lng:d[8],online:d[9],active:d[10]})); }
function makeRide(i,status,pick,drop,driver,extra={}){ const miles=+dist(places[pick],places[drop]).toFixed(1); const f=+(6+miles*1.5).toFixed(2); return {id:"OR-"+(1042-i),customer:names[i],phone:"918-555-"+String(2000+i),pickup:pick,dropoff:drop,miles,estimate:f,finalFare:f,tip:0,status,driver,requested:i%5===0?"Tomorrow 9:15 AM":"Today "+(8+i%11)+":1"+i%10+" AM",late:0,escalated:false,...extra}; }
function seedRides(){
  const rows=[
    ["Pending",0,2,null],["Pending",4,1,null],["Accepted",6,5,"D3"],["Arriving",2,7,"D4"],["In progress",1,3,"D5"],["Accepted",7,0,"D6"],["Pending",5,2,null],["Pending",3,6,null],
    ["Completed",0,4,"D1"],["Completed",2,6,"D2"],["Completed",7,1,"D3"],["Completed",4,0,"D4"],["Cancelled",6,3,null],["Completed",1,5,"D5"],["Completed",3,7,"D6"],
    ["Completed",0,6,"D1"],["Completed",5,1,"D2"],["Completed",2,4,"D3"],["Completed",7,3,"D4"],["Completed",6,0,"D5"],["Completed",1,7,"D6"],["Completed",4,2,"D1"],
    ["Completed",3,0,"D2"],["Completed",0,1,"D3"],["Completed",2,5,"D4"],["Completed",5,6,"D5"],["Completed",6,4,"D6"],["Completed",1,2,"D1"]
  ];
  return rows.map((r,i)=>makeRide(i,r[0],r[1],r[2],r[3], i>7&&r[0]==="Completed"?{tip:i%3===0?3:0}:{}));
}
function resetState(){ state={view:"owner",tab:"Dispatch",drivers:seedDrivers(),rides:seedRides(),pricing:{base:6,mile:1.5,timeout:4},messages:["Welcome to the owner preview.","Sample day loaded with 28 rides."],toast:null,selectedDriver:"D1",customerRide:"OR-1042",bookingOpen:false,tour:null,historySearch:"",historyStatus:"All",booking:{mode:"now",pickup:0,dropoff:2,time:""}}; }
const tourSteps=[
  ["owner","Dispatch","Welcome to your operation","Explore a busy sample day: 28 rides and 8 drivers. Use Next for the owner walkthrough, or exit and try anything."],
  ["customer",null,"A customer requests a ride","Maya can request now or schedule within 48 hours, choose McAlester locations, and see the card-only fare estimate."],
  ["driver",null,"Everyone online gets the request","Available drivers see pending requests and accept one. The first driver to accept gets it."],
  ["customer",null,"The customer sees who is coming","Assigned driver details, vehicle, plate, route and map are visible once accepted."],
  ["driver",null,"From pickup to completion","Drivers call, send late updates, arrive, start, and complete card fares in the demo."],
  ["customer",null,"History and tips","Completed rides go to history and the customer can leave a separate demo tip."],
  ["owner","Dispatch","Dispatch without the guesswork","Pending, assigned and on-trip lanes show what needs attention."],
  ["owner","Drivers","Manage your team","Add drivers, edit vehicles, and deactivate only when no active trip is assigned."],
  ["owner","Revenue","Pricing and the 10% agreement","Edit future rates and see completed fares, tips, and commission totals."],
  ["owner","Dispatch","Ready for free explore","This is session-only: no real accounts, payments, SMS, phone calls, or GPS are created."]
];
function icon(name){ const m={car:"🚘",bell:"🔔",play:"▷",reset:"↺",phone:"☎",check:"✓",map:"⌖",wallet:"▣",users:"☷",cal:"□",next:"›"}; return m[name]||""; }
function initials(n){return n.split(" ").map(x=>x[0]).slice(0,2).join("");}
function activeRides(){return state.rides.filter(r=>!["Completed","Cancelled"].includes(r.status));}
function terminal(r){return ["Completed","Cancelled"].includes(r.status);}
function onlineDrivers(){return state.drivers.filter(d=>d.active&&d.online);}
function driverBusy(id){return activeRides().some(r=>r.driver===id);}
function available(d){return d.active&&d.online&&!driverBusy(d.id);}
function completed(){return state.rides.filter(r=>r.status==="Completed");}
function fareRevenue(){return completed().reduce((s,r)=>s+r.finalFare,0);}
function tips(){return completed().reduce((s,r)=>s+(+r.tip||0),0);}
function commission(){return completed().reduce((s,r)=>s+Math.round(r.finalFare*10)/100,0);}
function say(msg){ state.messages.unshift(msg); showToast(msg); render(); }
function showToast(msg){ toastEl.textContent=msg; toastEl.hidden=false; clearTimeout(showToast.t); showToast.t=setTimeout(()=>toastEl.hidden=true,5000); }
function setView(v){ state.view=v; if(v==="owner"&&!state.tab) state.tab="Dispatch"; closeModal(); render(); window.scrollTo({top:0,behavior:"smooth"}); }
function changeRide(id, patch, msg){ const r=state.rides.find(x=>x.id===id); Object.assign(r,patch); if(msg) say(msg); else render(); }
function routeHtml(r){return `<div class="route"><p><i></i>${places[r.pickup].name}</p><p><i></i>${places[r.dropoff].name}</p></div>`}
function badge(s){return `<span class="badge badge-${String(s).toLowerCase().replaceAll(" ","-")}">${s}</span>`}
function render(){
  app.innerHTML = `${topbar()}${demoBar()}${state.view==="owner"?ownerView():state.view==="customer"?customerView():driverView()}${tour()}${footer()}`;
  bind();
  renderMaps();
}
function topbar(){return `<header class="topbar"><button class="brand" data-action="home"><span class="brand-mark">O</span><span><span class="brand-main">okie</span><span class="brand-sub">RIDESHARE</span></span></button><nav class="role-nav">${["Customer","Driver","Owner"].map(v=>`<button class="${state.view===v.toLowerCase()?"active":""}" data-view="${v.toLowerCase()}">${v}${v==="Owner"?" dashboard":""}</button>`).join("")}</nav><div class="header-actions"><button class="bell" data-modal="messages" aria-label="Notifications">${icon("bell")}<span class="bell-dot"></span></button><span class="avatar">OK</span></div></header>`}
function demoBar(){return `<div class="demo-bar"><span><strong>Owner preview</strong> All rides, calls and payments are simulated.</span><span class="demo-actions"><button class="link-action" data-action="tour">${icon("play")} Guided tour</button><button class="link-action" data-modal="reset">${icon("reset")} Reset demo</button></span></div>`}
function ownerView(){
  const active=activeRides(), waiting=active.filter(r=>r.status==="Pending").length, online=onlineDrivers().length;
  return `<main class="page"><section class="owner-hero"><div class="hero-copy"><p class="eyebrow">McAlester, Oklahoma · Open 24/7</p><h1>A clear view of every ride.</h1><p class="subtle">Your dispatch desk, your drivers, your town.</p><div class="hero-actions"><button class="button primary" data-modal="pricing">Manage pricing ${icon("next")}</button></div></div><div class="metric-stack">
    ${metric("Active rides",active.length,waiting+" waiting for a driver","car")}
    ${metric("Drivers online",online+" / "+state.drivers.filter(d=>d.active).length,"Expanded fleet preview","users")}
    ${metric("Website fare revenue",money(fareRevenue()),completed().length+" completed rides","wallet")}
    ${metric("Commission owed",money(commission()),"10% of fares · tips excluded","check","highlight")}
  </div></section><nav class="tabs">${["Dispatch","Drivers","Revenue"].map(t=>`<button data-tab="${t}" class="${state.tab===t?"active":""}">${t}</button>`).join("")}</nav>${state.tab==="Dispatch"?dispatchTab():state.tab==="Drivers"?driversTab():revenueTab()}</main>`;
}
function metric(label,value,sub,ic,cls=""){return `<div class="metric ${cls}"><small>${icon(ic)} ${label}</small><strong>${value}</strong><small>${sub}</small></div>`}
function dispatchTab(){
  const active=activeRides(), pending=active.filter(r=>r.status==="Pending"), assigned=active.filter(r=>["Accepted","Arriving"].includes(r.status)), trip=active.filter(r=>r.status==="In progress");
  return `<section class="dispatch-grid"><div class="panel fleet-map"><div data-map="fleet" class="map-shell"></div></div><aside class="panel"><div class="section-head"><h2>On the road</h2>${badge("Demo")}</div>${onlineDrivers().map(d=>`<button class="driver-line" data-driver-preview="${d.id}"><span class="person-dot">${initials(d.name)}</span><span class="grow"><b>${d.name}</b><small>${d.color} ${d.make} ${d.model}</small></span><span class="availability ${available(d)?"free":""}">${available(d)?"Available":"On trip"}</span></button>`).join("")}</aside></section><section><div class="section-head"><div><h2>Dispatch board <span class="badge">${active.length}</span></h2><p>Open a ride to assign, track or update it.</p></div><button class="button secondary" data-action="escalate">Simulate unclaimed request</button></div><div class="board">${lane("Pending",pending)}${lane("Assigned",assigned)}${lane("On trip",trip)}</div></section>`
}
function lane(name,rides){return `<div class="lane"><h3>${name}<span>${rides.length}</span></h3>${rides.length?rides.map(rideCard).join(""):`<p class="empty">No ${name.toLowerCase()} rides.</p>`}</div>`}
function rideCard(r){let cls=r.status==="Pending"?"":r.status==="In progress"?"ontrip":"assigned";return `<button class="ride-card ${cls}" data-ride="${r.id}"><div class="card-meta"><span>${r.id}</span><span>${r.escalated?"Needs attention":r.status}</span></div><strong>${r.customer}</strong>${routeHtml(r)}<div class="card-bottom"><span>${r.driver?state.drivers.find(d=>d.id===r.driver)?.name.split(" ")[0]:"Awaiting driver"}</span><b>${money(r.estimate)}</b></div>${r.late?`<small class="availability">${r.late} min late · customer updated</small>`:""}</button>`}
function driversTab(){return `<section class="section-head"><div><h2>Driver team</h2><p>Manage the seeded driver roster for the owner walkthrough.</p></div><button class="button primary" data-modal="addDriver">Add driver</button></section><div class="driver-cards">${state.drivers.map(d=>`<article class="team-card"><span class="person-dot">${initials(d.name)}</span><h3>${d.name}</h3><p>${d.color} ${d.make} ${d.model}</p><p>${d.plate} · ${d.phone}</p>${badge(!d.active?"Inactive":d.online?"Online":"Offline")}<div class="team-actions"><button class="button secondary" data-edit-driver="${d.id}">Manage/Edit</button><button class="button ${d.active?"danger-btn":"secondary"}" data-toggle-active="${d.id}">${d.active?"Deactivate":"Reactivate"}</button></div></article>`).join("")}</div>`}
function revenueTab(){const fares=fareRevenue(), tip=tips(); return `<section class="revenue-layout"><div class="panel"><div class="section-head"><div><h2>Revenue report</h2><p>Completed website rides only.</p></div><button class="button primary" data-action="csv">Export report</button></div><div class="bars">${completed().slice(0,10).map(r=>`<div class="bar"><span>${r.id}</span><span class="bar-track"><i style="width:${Math.min(100,r.finalFare/35*100)}%"></i></span><b>${money(r.finalFare)}</b></div>`).join("")}</div><div class="history-list">${completed().slice(0,8).map(r=>`<button class="history-row" data-ride="${r.id}"><span class="grow"><b>${r.customer}</b><small>${places[r.pickup].name} → ${places[r.dropoff].name}</small></span><b>${money(r.finalFare)}</b></button>`).join("")}</div></div><aside class="panel"><h2>Current pricing</h2><p class="subtle">${money(state.pricing.base)} base + ${money(state.pricing.mile)}/mile</p><button class="button secondary" data-modal="pricing">Edit rates</button><div class="receipt"><div><span>Completed fares</span><b>${money(fares)}</b></div><div><span>Tips</span><b>${money(tip)}</b></div><div><span>Commission</span><strong>${money(commission())}</strong></div></div></aside></section>`}
function customerView(){
  const r=state.rides.find(x=>x.id===state.customerRide)||state.rides[0], completedRide=r.status==="Completed";
  return `<main class="page customer-layout"><section class="customer-panel"><p class="eyebrow">Customer preview</p><h1>Where to, Maya?</h1><div class="account-line"><span class="person-dot">MT</span><span><b>Maya Thompson</b><br><small class="subtle">918-555-2000 · card paid to driver</small></span></div>${state.bookingOpen?bookingForm():activeRidePanel(r)}<p class="notice">${icon("wallet")} Card-only payment is collected in person by the driver. No in-app payment is simulated.</p><div class="section-head"><h2>Recent rides</h2><button class="link-action" data-modal="history">View all</button></div><div class="history-list">${state.rides.filter(x=>x.customer==="Maya Thompson"||x.status==="Completed").slice(0,4).map(x=>`<button class="history-row" data-ride="${x.id}"><span class="grow"><b>${x.id} · ${x.status}</b><small>${places[x.pickup].name} → ${places[x.dropoff].name}</small></span><b>${money(x.finalFare||x.estimate)}</b></button>`).join("")}</div></section><section class="map-column"><div data-map="customer" data-ride-id="${r.id}" class="map-shell"></div><div class="panel" style="margin-top:14px"><b>${completedRide?"Completed trip":"Current route"}</b><p class="subtle">${places[r.pickup].name} → ${places[r.dropoff].name}</p></div></section></main>`;
}
function bookingForm(){const b=state.booking, mi=+dist(places[b.pickup],places[b.dropoff]).toFixed(1), est=fare(mi), no=!onlineDrivers().length;return `<div class="segment"><button class="${b.mode==="now"?"active":""}" data-book-mode="now">Request now</button><button class="${b.mode==="later"?"active":""}" data-book-mode="later">Schedule ahead</button></div><div class="field-grid"><label class="field">Pickup<select data-book="pickup">${places.map(p=>`<option value="${p.id}" ${p.id==b.pickup?"selected":""}>${p.name}</option>`).join("")}</select></label><label class="field">Dropoff<select data-book="dropoff">${places.map(p=>`<option value="${p.id}" ${p.id==b.dropoff?"selected":""}>${p.name}</option>`).join("")}</select></label></div>${b.mode==="later"?`<label class="field">Pickup time within 48 hours<input type="datetime-local" data-book="time" value="${b.time}"></label>`:""}<div class="estimate"><span>Estimated fare</span><strong>${money(est)}</strong><small>${mi} sample miles · card paid to driver</small></div>${no?`<p class="notice">No drivers are online. The ride can stay pending for owner dispatch.</p>`:""}<button class="button primary" data-action="confirmRide">Confirm ride</button><button class="button secondary" data-action="closeBooking">Cancel</button>`}
function activeRidePanel(r){ const d=state.drivers.find(x=>x.id===r.driver); return `<div class="active-ride"><div>${badge(r.status)}</div>${routeHtml(r)}<div class="estimate"><span>${r.status==="Completed"?"Receipt total":"Fare estimate"}</span><strong>${money((r.finalFare||r.estimate)+(r.tip||0))}</strong><small>${r.miles} miles · ${r.id}</small></div>${d?`<div class="assigned"><span class="person-dot">${initials(d.name)}</span><span><b>${d.name}</b><br><small>${d.color} ${d.make} ${d.model} · ${d.plate}</small></span></div>`:"<p class='notice'>Waiting for an available driver to accept.</p>"}${r.late?`<p class="notice">Driver is running about ${r.late} minutes late.</p>`:""}<div class="button-row">${!terminal(r)?`<button class="button danger-btn" data-action="cancelCustomer">Cancel ride</button>`:""}${r.status==="Completed"?`<button class="button primary" data-modal="tip">Leave a tip</button><button class="button secondary" data-action="newBooking">Book another ride</button>`:`<button class="button secondary" data-action="newBooking">Book another ride</button>`}</div></div>`}
function driverView(){const d=state.drivers.find(x=>x.id===state.selectedDriver), trip=activeRides().find(r=>r.driver===d.id), pending=state.rides.filter(r=>r.status==="Pending"); return `<main class="page"><div class="driver-top"><div class="driver-heading"><p class="eyebrow">Driver preview</p><h1>You're up, ${d.name.split(" ")[0]}.</h1></div><div class="driver-controls"><label class="field">Preview as driver<select data-select-driver>${state.drivers.map(x=>`<option value="${x.id}" ${x.id===d.id?"selected":""}>${x.name}</option>`).join("")}</select></label><button class="button ${d.online?"secondary":"primary"}" data-action="toggleOnline" ${!d.active?"disabled":""}>Go ${d.online?"offline":"online"}</button></div></div><section class="driver-layout"><div class="driver-panel">${trip?tripPanel(trip,d):`<h2>No current trip</h2><p class="subtle">Accept a pending request to preview the driver flow.</p>`}<div class="vehicle-card"><h2>Vehicle</h2><p>${d.color} ${d.make} ${d.model}<br>${d.plate}</p><button class="button secondary" data-edit-driver="${d.id}">Edit vehicle</button></div></div><div data-map="driver" data-ride-id="${trip?.id||pending[0]?.id||""}" class="map-shell"></div></section><section style="margin-top:28px"><div class="section-head"><h2>Available requests</h2><p>First driver to accept gets it.</p></div><div class="request-grid">${pending.length?pending.map(r=>`<article class="team-card"><div>${badge(r.escalated?"Escalated":"Pending")}</div><h3>${r.customer}</h3>${routeHtml(r)}<p>${money(r.estimate)} · ${r.miles} mi</p><button class="button primary" data-accept="${r.id}" ${!available(d)?"disabled":""}>Accept</button></article>`).join(""):`<p class="empty">No pending requests.</p>`}</div></section></main>`}
function tripPanel(r,d){return `<h2>Current trip</h2>${badge(r.status)}<h3>${r.customer}</h3>${routeHtml(r)}<div class="receipt"><div><span>Mileage</span><b>${r.miles} mi</b></div><div><span>Estimate</span><b>${money(r.estimate)}</b></div></div><div class="button-row"><button class="button secondary" data-modal="call">${icon("phone")} Call customer</button><button class="button secondary" data-modal="late">Running late</button>${r.status==="Accepted"?`<button class="button primary" data-action="arrive">I'm here</button>`:""}${r.status==="Arriving"?`<button class="button primary" data-action="startRide">Start ride</button>`:""}${r.status==="In progress"?`<button class="button primary" data-modal="complete">Complete ride</button>`:""}<button class="button danger-btn" data-action="cancelDriver">Cancel accepted ride</button></div>`}
function footer(){return `<footer class="site-footer"><span>Okie Rideshare owner preview · session-only demo</span><span>No real payment, call, SMS, account, or GPS action is created.</span></footer>`}
function tour(){ if(state.tour==null) return ""; const s=tourSteps[state.tour]; return `<aside class="tour"><div class="tour-dots">${tourSteps.map((_,i)=>`<button class="${i<=state.tour?"active":""}" data-tour-jump="${i}"></button>`).join("")}</div><div class="tour-body"><div><p class="eyebrow">Step ${state.tour+1} of ${tourSteps.length}</p><h2>${s[2]}</h2><p>${s[3]}</p></div><div class="modal-actions"><button class="button secondary" data-action="tourExit">Explore freely</button><button class="button secondary" data-action="tourBack" ${state.tour===0?"disabled":""}>Back</button><button class="button primary" data-action="tourNext">${state.tour===tourSteps.length-1?"Finish":"Next"}</button></div></div></aside>`}
function bind(){
  document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));
  $("[data-action='home']")?.addEventListener("click",()=>{state.view="owner";state.tab="Dispatch";render();});
  document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{state.tab=b.dataset.tab;render();});
  document.querySelectorAll("[data-modal]").forEach(b=>b.onclick=()=>openModal(b.dataset.modal));
  document.querySelectorAll("[data-ride]").forEach(b=>b.onclick=()=>openRide(b.dataset.ride));
  document.querySelectorAll("[data-driver-preview]").forEach(b=>b.onclick=()=>{state.selectedDriver=b.dataset.driverPreview;setView("driver")});
  document.querySelectorAll("[data-edit-driver]").forEach(b=>b.onclick=()=>openDriverEditor(b.dataset.editDriver));
  document.querySelectorAll("[data-toggle-active]").forEach(b=>b.onclick=()=>toggleActive(b.dataset.toggleActive));
  document.querySelectorAll("[data-book-mode]").forEach(b=>b.onclick=()=>{state.booking.mode=b.dataset.bookMode;render();});
  document.querySelectorAll("[data-book]").forEach(el=>el.onchange=()=>{state.booking[el.dataset.book]=el.value.match(/pickup|dropoff/)?+el.value:el.value;render();});
  $("[data-action='confirmRide']")?.addEventListener("click",confirmRide);
  $("[data-action='closeBooking']")?.addEventListener("click",()=>{state.bookingOpen=false;render();});
  $("[data-action='newBooking']")?.addEventListener("click",()=>{state.bookingOpen=true;render();});
  $("[data-action='cancelCustomer']")?.addEventListener("click",()=>{changeRide(state.customerRide,{status:"Cancelled",driver:null},"Ride cancelled. No fee charged.");});
  $("[data-action='escalate']")?.addEventListener("click",()=>{const r=state.rides.find(x=>x.status==="Pending"&&!x.escalated); r?changeRide(r.id,{escalated:true},`${r.id} timed out after ${state.pricing.timeout} minutes. Owner alerted.`):say("Every pending request has already been escalated.");});
  $("[data-action='csv']")?.addEventListener("click",exportCsv);
  $("[data-select-driver]")?.addEventListener("change",e=>{state.selectedDriver=e.target.value;render();});
  $("[data-action='toggleOnline']")?.addEventListener("click",()=>{const d=state.drivers.find(x=>x.id===state.selectedDriver);d.online=!d.online;say(`${d.name} is ${d.online?"online":"offline"}.`);});
  document.querySelectorAll("[data-accept]").forEach(b=>b.onclick=()=>acceptRide(b.dataset.accept));
  $("[data-action='arrive']")?.addEventListener("click",()=>driverPatch("Arriving","Driver marked arrival."));
  $("[data-action='startRide']")?.addEventListener("click",()=>driverPatch("In progress","Ride started."));
  $("[data-action='cancelDriver']")?.addEventListener("click",()=>{const r=activeRides().find(x=>x.driver===state.selectedDriver); if(r) changeRide(r.id,{status:"Cancelled",driver:null},"Accepted ride cancelled.");});
  $("[data-action='tour']")?.addEventListener("click",()=>{state.tour=0;applyTour();});
  $("[data-action='tourExit']")?.addEventListener("click",()=>{state.tour=null;render();});
  $("[data-action='tourBack']")?.addEventListener("click",()=>{state.tour=Math.max(0,state.tour-1);applyTour();});
  $("[data-action='tourNext']")?.addEventListener("click",()=>{ if(state.tour===tourSteps.length-1) state.tour=null; else state.tour++; applyTour();});
  document.querySelectorAll("[data-tour-jump]").forEach(b=>b.onclick=()=>{state.tour=+b.dataset.tourJump;applyTour();});
}
function applyTour(){ if(state.tour==null){render();return;} const s=tourSteps[state.tour]; state.view=s[0]; if(s[1]) state.tab=s[1]; const r=state.rides.find(x=>x.id==="OR-1042"); if(state.tour===2) Object.assign(r,{status:"Pending",driver:null}); if(state.tour===3) Object.assign(r,{status:"Accepted",driver:"D1"}); if(state.tour===4) Object.assign(r,{status:"In progress",driver:"D1"}); if(state.tour===5) Object.assign(r,{status:"Completed",driver:"D1",finalFare:r.estimate}); state.customerRide="OR-1042"; state.selectedDriver="D1"; render(); }
function confirmRide(){ const b=state.booking; if(b.pickup===b.dropoff){showToast("Pickup and dropoff must be different.");return;} if(b.mode==="later"&&!b.time){showToast("Choose a pickup time within 48 hours.");return;} const mi=+dist(places[b.pickup],places[b.dropoff]).toFixed(1), f=fare(mi), id="OR-"+(1100+state.rides.length); const r={id,customer:"Maya Thompson",phone:"918-555-2000",pickup:b.pickup,dropoff:b.dropoff,miles:mi,estimate:f,finalFare:f,tip:0,status:"Pending",driver:null,requested:b.mode==="later"?"Scheduled":"Just now",late:0,escalated:false}; state.rides.unshift(r); state.customerRide=id; state.bookingOpen=false; say(`${id} requested. Drivers have been notified.`); }
function acceptRide(id){ const d=state.drivers.find(x=>x.id===state.selectedDriver); if(!available(d)){showToast("This driver is not available.");return;} changeRide(id,{status:"Accepted",driver:d.id},`${d.name} accepted ${id}. Customer updated.`); }
function driverPatch(status,msg){const r=activeRides().find(x=>x.driver===state.selectedDriver); if(r) changeRide(r.id,{status},msg);}
function toggleActive(id){ const d=state.drivers.find(x=>x.id===id); if(d.active&&driverBusy(id)){showToast("Reassign or finish the active trip before deactivating this driver.");return;} d.active=!d.active; if(!d.active)d.online=false; say(`${d.name} ${d.active?"reactivated":"deactivated"}.`); }
function exportCsv(){ const rows=[["Ride","Customer","Pickup","Dropoff","Fare","Tip","Commission"]].concat(completed().map(r=>[r.id,r.customer,places[r.pickup].name,places[r.dropoff].name,r.finalFare,r.tip||0,(Math.round(r.finalFare*10)/100).toFixed(2)])); const csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"); const a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"})); a.download="okie-rideshare-report.csv"; a.click(); say("CSV report downloaded."); }
function openModal(kind){ const html = modalContent(kind); modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal">${html}</div></div>`; modalRoot.querySelector("[data-close]")?.addEventListener("click",closeModal); modalRoot.querySelector("[data-confirm-reset]")?.addEventListener("click",()=>{resetState();closeModal();say("Fresh sample day loaded.");});
  modalRoot.querySelector("[data-save-pricing]")?.addEventListener("click",()=>{state.pricing.base=+$("#base").value;state.pricing.mile=+$("#mile").value;state.pricing.timeout=+$("#timeout").value;closeModal();say("Pricing updated for new ride requests.");});
  modalRoot.querySelector("[data-save-tip]")?.addEventListener("click",()=>{const r=state.rides.find(x=>x.id===state.customerRide);r.tip=+$("#tip").value||0;closeModal();say(`Tip updated to ${money(r.tip)}.`);});
  modalRoot.querySelector("[data-start-call]")?.addEventListener("click",()=>{$(".call-state").textContent="Connected in demo";});
  modalRoot.querySelector("[data-late]")?.addEventListener("click",()=>{const r=activeRides().find(x=>x.driver===state.selectedDriver); if(r){r.late=+$("#delay").value;closeModal();say(`Customer notified: driver is ${r.late} minutes late.`);}});
  modalRoot.querySelector("[data-complete]")?.addEventListener("click",()=>{const r=activeRides().find(x=>x.driver===state.selectedDriver); if(r){r.status="Completed";r.finalFare=+$("#finalFare").value||r.estimate;r.tip=+$("#completeTip").value||0;r.miles=+$("#miles").value||r.miles;closeModal();say(`${r.id} completed. Receipt and revenue updated.`);}});
  modalRoot.querySelector("[data-add-driver]")?.addEventListener("click",()=>saveDriver());
  modalRoot.querySelectorAll("[data-pick-history]").forEach(b=>b.onclick=()=>{state.customerRide=b.dataset.pickHistory;closeModal();render();});
}
function closeModal(){ modalRoot.innerHTML=""; }
function modalContent(kind){ if(kind==="messages")return `<h2>Demo messages</h2><div>${state.messages.map(m=>`<p>${m}</p>`).join("")}</div><div class="modal-actions"><button class="button primary" data-close>Close</button></div>`;
 if(kind==="reset")return `<h2>Reset demo?</h2><p>This restores all seeded rides, drivers, prices, messages, and tour state.</p><div class="modal-actions"><button class="button secondary" data-close>Keep exploring</button><button class="button danger-btn" data-confirm-reset>Reset demo</button></div>`;
 if(kind==="pricing")return `<h2>Manage pricing</h2><label class="field">Base fare<input id="base" type="number" step=".25" value="${state.pricing.base}"></label><label class="field">Per-mile rate<input id="mile" type="number" step=".05" value="${state.pricing.mile}"></label><label class="field">Unclaimed timeout minutes<input id="timeout" type="number" value="${state.pricing.timeout}"></label><div class="modal-actions"><button class="button secondary" data-close>Cancel</button><button class="button primary" data-save-pricing>Save rates</button></div>`;
 if(kind==="history"){const rides=state.rides.filter(r=>r.customer==="Maya Thompson"||r.status==="Completed");return `<h2>Ride history</h2><div class="history-list">${rides.map(r=>`<button class="history-row" data-pick-history="${r.id}"><span class="grow"><b>${r.id} · ${r.status}</b><small>${r.customer} · ${places[r.pickup].name} → ${places[r.dropoff].name}</small></span><b>${money(r.finalFare||r.estimate)}</b></button>`).join("")}</div><div class="modal-actions"><button class="button primary" data-close>Close</button></div>`}
 if(kind==="tip")return `<h2>Leave a tip</h2><p>Tips are recorded separately and excluded from commission.</p><label class="field">Tip amount<input id="tip" type="number" step="1" value="5"></label><div class="modal-actions"><button class="button secondary" data-close>Cancel</button><button class="button primary" data-save-tip>Save tip</button></div>`;
 if(kind==="call")return `<div class="call-panel"><h2>Simulated call</h2><p class="call-state">Ready to connect in demo.</p><div class="modal-actions"><button class="button secondary" data-close>End</button><button class="button primary" data-start-call>Start demo call</button></div></div>`;
 if(kind==="late")return `<h2>Running late</h2><label class="field">Delay<select id="delay"><option>5</option><option>10</option><option>15</option><option>20</option></select></label><div class="modal-actions"><button class="button secondary" data-close>Cancel</button><button class="button primary" data-late>Notify customer</button></div>`;
 if(kind==="complete"){const r=activeRides().find(x=>x.driver===state.selectedDriver);return `<h2>Complete ride</h2><label class="field">Final card fare<input id="finalFare" type="number" step=".01" value="${r?.estimate||0}"></label><label class="field">Tip collected<input id="completeTip" type="number" step="1" value="0"></label><label class="field">Mileage<input id="miles" type="number" step=".1" value="${r?.miles||0}"></label><p><label><input type="checkbox" checked> Card payment confirmed in person</label></p><div class="modal-actions"><button class="button secondary" data-close>Cancel</button><button class="button primary" data-complete>Complete ride</button></div>`}
 if(kind==="addDriver")return driverForm();
 return `<h2>Demo</h2><p>Nothing to show.</p><button class="button primary" data-close>Close</button>`}
function openRide(id){ const r=state.rides.find(x=>x.id===id), eligible=state.drivers.filter(available); modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal"><h2>${r.id}</h2>${badge(r.status)}${routeHtml(r)}<p>${r.customer} · ${money(r.finalFare||r.estimate)}</p><label class="field">Assign driver<select id="assignDriver"><option value="">Unassigned</option>${state.drivers.filter(d=>d.active&&d.online).map(d=>`<option value="${d.id}" ${r.driver===d.id?"selected":""}>${d.name}${available(d)||r.driver===d.id?"":" (busy)"}</option>`).join("")}</select></label><div class="modal-actions"><button class="button secondary" data-close>Close</button><button class="button danger-btn" data-cancel-ride>Cancel ride</button><button class="button primary" data-save-ride>Save assignment</button></div></div></div>`;
 $("#modal-root [data-close]").onclick=closeModal; $("[data-cancel-ride]",modalRoot).onclick=()=>{Object.assign(r,{status:"Cancelled",driver:null});closeModal();say(`${r.id} cancelled.`)}; $("[data-save-ride]",modalRoot).onclick=()=>{const id=$("#assignDriver").value; const d=state.drivers.find(x=>x.id===id); if(id&&driverBusy(id)&&r.driver!==id){showToast("That driver is already on an active ride.");return;} r.driver=id||null; if(id&&r.status==="Pending")r.status="Accepted"; closeModal();say(`${r.id} assignment updated.`);};}
function openDriverEditor(id){ modalRoot.innerHTML=`<div class="modal-backdrop"><div class="modal">${driverForm(id)}</div></div>`; $("[data-close]",modalRoot).onclick=closeModal; $("[data-add-driver]",modalRoot).onclick=()=>saveDriver(id); }
function driverForm(id){ const d=state.drivers.find(x=>x.id===id)||{name:"",phone:"",make:"",model:"",color:"",plate:""}; return `<h2>${id?"Edit driver":"Add driver"}</h2>${["name","phone","make","model","color","plate"].map(k=>`<label class="field">${k}<input id="drv-${k}" value="${d[k]||""}"></label>`).join("")}<div class="modal-actions"><button class="button secondary" data-close>Cancel</button><button class="button primary" data-add-driver>${id?"Save changes":"Add driver"}</button></div>`}
function saveDriver(id){ let d=state.drivers.find(x=>x.id===id); if(!d){d={id:"D"+(state.drivers.length+1),online:false,active:true,lat:34.93,lng:-95.76};state.drivers.push(d);} ["name","phone","make","model","color","plate"].forEach(k=>d[k]=$("#drv-"+k).value); closeModal(); say(`${d.name} saved.`); }
let maps=[]; const roadLines=[[[34.885,-95.783],[34.91,-95.778],[34.936,-95.771],[34.958,-95.765],[34.985,-95.758]],[[34.926,-95.82],[34.928,-95.795],[34.93,-95.765],[34.932,-95.735],[34.936,-95.706]],[[34.895,-95.752],[34.918,-95.754],[34.945,-95.756],[34.971,-95.758]],[[34.904,-95.792],[34.922,-95.777],[34.942,-95.756],[34.962,-95.737]],[[34.906,-95.727],[34.926,-95.744],[34.948,-95.763],[34.968,-95.782]]];
function renderMaps(){ maps=[]; document.querySelectorAll("[data-map]").forEach(el=>drawMap(el)); }
function drawMap(el){ el.innerHTML=`<div class="map-standby"></div><div class="live-map"></div><div class="map-caption">McAlester, OK<span>Drag to explore · scroll or pinch to zoom</span></div><button class="map-reset">Recenter</button><div class="map-demo">Sample positions · illustrative route</div>`; if(!window.L){el.innerHTML+=`<div class="map-error">Map could not load. <button class="button secondary" onclick="location.reload()">Retry map</button></div>`;return;} const target=$(".live-map",el), map=L.map(target,{scrollWheelZoom:true,zoomControl:false}).setView([34.935,-95.761],13); maps.push(map); L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:19,attribution:"&copy; OpenStreetMap"}).addTo(map); L.control.zoom({position:"bottomright"}).addTo(map); roadLines.forEach((r,i)=>{L.polyline(r,{color:"#fff",weight:i<2?8:6,opacity:.9}).addTo(map);L.polyline(r,{color:i<2?"#c96d38":"#78977f",weight:i<2?3:2,opacity:.9}).addTo(map);}); ["Downtown","McAlester","Alderson"].forEach((t,i)=>L.marker([[34.933,-95.769],[34.922,-95.73],[34.901,-95.768]][i],{icon:L.divIcon({className:"map-label",html:t})}).addTo(map)); const ride=state.rides.find(r=>r.id===el.dataset.rideId)||activeRides()[0]; state.drivers.filter(d=>d.active&&d.online&&(el.dataset.map==="fleet"||!ride||d.id===ride.driver)).forEach(d=>{L.marker([d.lat,d.lng],{icon:L.divIcon({className:"fleet-marker",html:`<span>${d.id.replace(/\D/g,"")}</span>`,iconSize:[34,34],iconAnchor:[17,17]})}).bindPopup(`${d.name} · ${d.color} ${d.make} ${d.model}`).addTo(map);}); if(ride){const a=places[ride.pickup],b=places[ride.dropoff], route=[[a.lat,a.lng],[b.lat,b.lng]]; L.marker(route[0],{icon:L.divIcon({className:"trip-pin pin-pickup",html:"<span></span>",iconSize:[34,42],iconAnchor:[17,38]})}).bindPopup("Pickup: "+a.name).addTo(map); L.marker(route[1],{icon:L.divIcon({className:"trip-pin pin-dropoff",html:"<span></span>",iconSize:[34,42],iconAnchor:[17,38]})}).bindPopup("Dropoff: "+b.name).addTo(map); L.polyline(route,{color:"#fff",weight:9,opacity:.85}).addTo(map); L.polyline(route,{color:"#bd542e",weight:4,dashArray:"8 7"}).bindTooltip("Illustrative trip connection · not a calculated route").addTo(map);} $(".map-reset",el).onclick=()=>map.setView([34.935,-95.761],13); setTimeout(()=>map.invalidateSize(),50); }
resetState(); render();
